### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [Juanmalopezg/smooth-distortion#3]
Hi there, 1st of all thanks for this awesome work !

Since we've 'doxed' it in our [HyMPS project](https://forart.it/HyMPS) (under [AUDIO category](https://github.com/forart/HyMPS#- ) \ [Effects page](https://github.com/forart/HyMPS/blob/main/Audio/Effects.md#-- ) \ [Guitar section](https://github.com/forart/HyMPS/blob/main/Audio/Guitar.md#--- ) \ [Pedals subsection](https://github.com/forart/HyMPS/blob/main/Audio/GPedals.md#---- ) \ [Distorsion](https://github.com/forart/HyMPS/blob/main/Audio/GPedals.md#distorsion-)), can you please add a GH-compliant license file for it ?

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/Juanmalopezg/smooth-distortion/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/Juanmalopezg/smooth-distortion/?label=LICENSE)

Anyway you can easily set a standardized one through the GH's license wizard tool.

Last but not least, let us know how we could improve - in your opinion - our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Hope that helps/inspires !

**Comment by Juanmalopezg** [comment]
Hi, I've already pushed a GNU GPL v3 license. I'll leave the issue open while the badge generator still shows the no-license label. Let me know if there's anything else I should do 🙂

**Comment by MarcoRavich** [comment]
Works now, thanks !
